"""execubench command line.

python -m execubench models scan                       pin every XNNPACK .pte on the Hub
python -m execubench datasets stats                    recount every dataset figure the docs cite
python -m execubench budget                            the v1 device-minute budget (docs/PLAN.md 7.2)
python -m execubench devicefarm probe <project> <pool> --carrier-apk carrier.apk
python -m execubench devicefarm pull <run-arn> <new folder>
python -m execubench devices build <probe-run>...      parse dumps, write devices.json (oldest run first)
python -m execubench devices table                     regenerate the table in docs/DEVICES.md
python -m execubench host run <pte> <tokenizer> --out r.json   needs requirements/host.txt
python -m execubench host compare a.json b.json        exit 3 when two runtimes disagree
python -m execubench host summary <folder>             SUMMARY.md for a folder of compare results
python -m execubench validate                          check generated files against schemas/
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROBE_TIMEOUT_MIN = 15
PROBE_PYTEST_PIN = "pytest==9.1.1"


def _models_scan(args) -> int:
    from . import models

    inv = models.scan()
    out = {
        "scanned_utc": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "note": "Generated by execubench models scan; do not edit by hand.",
        "files": inv,
    }
    problems = models.problems(inv)
    target = Path(args.out)
    # A scan with problems never replaces the accepted inventory; it is kept beside it for diagnosis.
    if problems:
        rejected = target.with_suffix(".rejected.json")
        rejected.write_text(json.dumps({**out, "problems": problems}, indent=1) + "\n")
        print(f"{len(problems)} problems; {target} left unchanged, scan written to {rejected}")
        for line in problems[:20]:
            print("  " + line)
        return 1
    tmp = target.with_suffix(".tmp")
    tmp.write_text(json.dumps(out, indent=1) + "\n")
    tmp.replace(target)
    print(f"{len(inv)} files, {len({f['repo'] for f in inv})} repos -> {target}")
    return 0


def _devicefarm_pull(args) -> int:
    from . import devicefarm, devices

    names = devices.kernel_part_names()
    dest = Path(args.dest)
    manifest = devicefarm.pull_run(
        devicefarm.client(), args.run_arn, dest, allow_incomplete=args.allow_incomplete, restart=args.restart
    )
    for name, job in sorted(manifest["jobs"].items()):
        probe = dest / name / "artifacts" / "probe"
        if probe.exists():
            (dest / name / "profile.json").write_text(json.dumps(devices.profile(probe, names), indent=1) + "\n")
        print(f"{job['state']:<13} {job['result'] or '-':<8} {name}")
    # An incomplete pull (allowed explicitly) still exits non-zero, so scripts cannot mistake it.
    return 0 if manifest["complete"] else 2


def _devicefarm_probe(args) -> int:
    import tempfile
    import zipfile

    from . import devicefarm

    df = devicefarm.client()
    here = ROOT / "devicefarm" / "probe"
    with tempfile.TemporaryDirectory() as tmp:
        pkg = Path(tmp) / "probe_pkg.zip"
        with zipfile.ZipFile(pkg, "w") as z:
            # Device Farm's Appium Python package needs a requirements file and a test; the probe
            # runs from the test spec and installs nothing, so the one requirement is pinned.
            z.writestr("requirements.txt", PROBE_PYTEST_PIN + "\n")
            z.write(here / "probe.sh", "tests/probe.sh")
            z.writestr("tests/test_probe.py", "def test_placeholder():\n    assert True\n")
        app = devicefarm.upload(df, args.project_arn, Path(args.carrier_apk), "ANDROID_APP")
        devices_in_pool = devicefarm.pool_devices(df, args.pool_arn, app, "APPIUM_PYTHON")
        worst = devicefarm.spend_guard(len(devices_in_pool), PROBE_TIMEOUT_MIN, args.max_device_minutes)
        print(f"{len(devices_in_pool)} devices, at most {worst:.0f} device minutes")
        test = devicefarm.upload(df, args.project_arn, pkg, "APPIUM_PYTHON_TEST_PACKAGE")
        spec = devicefarm.upload(df, args.project_arn, here / "testspec.yml", "APPIUM_PYTHON_TEST_SPEC")
    run = df.schedule_run(
        projectArn=args.project_arn,
        appArn=app,
        devicePoolArn=args.pool_arn,
        name=args.name,
        test={"type": "APPIUM_PYTHON", "testPackageArn": test, "testSpecArn": spec},
        # Screen recording competes for CPU and GPU on the phone; the probe and every
        # benchmark run without it.
        executionConfiguration={"jobTimeoutMinutes": PROBE_TIMEOUT_MIN, "videoCapture": False},
    )["run"]
    print(run["arn"])
    return 0


def _devices_build(args) -> int:
    from . import registry

    roots = [Path(d) for d in args.probe_dirs]
    recs = registry.build(roots)
    out = {"generated_from": [str(r) for r in roots] + ["data/devices/specs.yaml"], "devices": recs}
    Path(args.out).write_text(json.dumps(out, indent=1) + "\n")
    print(f"{len(recs)} device records -> {args.out}")
    return 0


def _datasets_stats(args) -> int:
    from . import datasets

    out = datasets.stats()
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(json.dumps(out, indent=1) + "\n")
    print(f"{len(out)} datasets -> {args.out}")
    return 0


def _budget(args) -> int:
    from . import budget

    print(json.dumps(budget.budget(), indent=1))
    return 0


def _devices_table(args) -> int:
    from . import registry

    recs = json.loads(Path(args.devices).read_text())["devices"]
    doc = Path(args.doc)
    text = doc.read_text()
    start, end = text.index(registry.TABLE_BEGIN), text.index(registry.TABLE_END)
    table = registry.markdown_table(recs)
    doc.write_text(text[: start + len(registry.TABLE_BEGIN)] + "\n\n" + table + "\n" + text[end:])
    print(f"{sum(r.get('latest_for_model', True) for r in recs)} rows -> {doc}")
    return 0


def _host_run(args) -> int:
    from . import host

    source = {k: v for k, v in (("repo", args.repo), ("revision", args.revision), ("file", args.file)) if v}
    report = host.run(Path(args.pte), Path(args.tokenizer), source=source)
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(json.dumps(report, indent=1) + "\n")
    print(f"executorch {report['executorch']}: {len(report['results'])} prompts -> {args.out}")
    return 0


def _host_compare(args) -> int:
    from . import host

    result = host.compare(json.loads(Path(args.a).read_text()), json.loads(Path(args.b).read_text()))
    print(json.dumps(result, indent=1))
    return 0 if result["identical"] else 3


def _host_summary(args) -> int:
    from . import host

    folder = Path(args.folder)
    (folder / "SUMMARY.md").write_text(host.summary_markdown(folder))
    print(f"-> {folder / 'SUMMARY.md'}")
    return 0


def _validate(args) -> int:
    from . import schemas

    errors = schemas.validate_repo()
    for e in errors:
        print(e)
    print("ok" if not errors else f"{len(errors)} errors")
    return 1 if errors else 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="execubench")
    sub = p.add_subparsers(dest="cmd", required=True)

    m = sub.add_parser("models").add_subparsers(dest="sub", required=True)
    s = m.add_parser("scan")
    s.add_argument("--out", default=str(ROOT / "data" / "models" / "xnnpack.json"))
    s.set_defaults(fn=_models_scan)

    d = sub.add_parser("devicefarm").add_subparsers(dest="sub", required=True)
    s = d.add_parser("pull")
    s.add_argument("run_arn")
    s.add_argument("dest", help="Must not exist; the pull is staged in <dest>.partial and renamed when complete")
    s.add_argument("--allow-incomplete", action="store_true", help="Keep a pull with missing jobs (exit 2)")
    s.add_argument("--restart", action="store_true", help="Move an unfinished <dest>.partial aside and pull again")
    s.set_defaults(fn=_devicefarm_pull)
    s = d.add_parser("probe")
    s.add_argument("project_arn")
    s.add_argument("pool_arn")
    s.add_argument("--carrier-apk", required=True, help="Any installable APK; the probe ignores it")
    s.add_argument(
        "--max-device-minutes",
        type=float,
        required=True,
        help="Refuse the run if pool size x job timeout exceeds this many device minutes",
    )
    s.add_argument("--name", default=f"probe-{datetime.now(UTC):%Y-%m-%d}")
    s.set_defaults(fn=_devicefarm_probe)

    v = sub.add_parser("devices").add_subparsers(dest="sub", required=True)
    s = v.add_parser("build")
    s.add_argument("probe_dirs", nargs="+", help="Probe run folders, oldest first; later runs win per device")
    s.add_argument("--out", default=str(ROOT / "data" / "devices" / "devices.json"))
    s.set_defaults(fn=_devices_build)

    t = sub.add_parser("datasets").add_subparsers(dest="sub", required=True)
    s = t.add_parser("stats")
    s.add_argument("--out", default=str(ROOT / "data" / "datasets" / "stats.json"))
    s.set_defaults(fn=_datasets_stats)

    h = sub.add_parser("host").add_subparsers(dest="sub", required=True)
    s = h.add_parser("run", help="Greedy pieces and runner stats for a .pte under this venv's executorch")
    s.add_argument("pte")
    s.add_argument("tokenizer")
    s.add_argument("--out", required=True)
    s.add_argument("--repo")
    s.add_argument("--revision")
    s.add_argument("--file")
    s.set_defaults(fn=_host_run)
    s = h.add_parser("compare", help="Exit 0 if two host reports agree piece for piece, 3 if not")
    s.add_argument("a")
    s.add_argument("b")
    s.set_defaults(fn=_host_compare)
    s = h.add_parser("summary", help="Write SUMMARY.md for a folder of host compare results")
    s.add_argument("folder")
    s.set_defaults(fn=_host_summary)

    s = sub.add_parser("budget")
    s.set_defaults(fn=_budget)

    s = v.add_parser("table")
    s.add_argument("--devices", default=str(ROOT / "data" / "devices" / "devices.json"))
    s.add_argument("--doc", default=str(ROOT / "docs" / "DEVICES.md"))
    s.set_defaults(fn=_devices_table)

    s = sub.add_parser("validate")
    s.set_defaults(fn=_validate)

    args = p.parse_args(argv)
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
