"""Run a `.pte` on this machine with ExecuTorch's own C++ `TextLLMRunner` (through its Python
bindings), greedy, and record every piece and the runner's stats.

This is the host side of the agreement track (docs/PLAN.md 6.4) and the runtime-upgrade check:
the same file and prompts under two ExecuTorch versions must give the same tokens before the
phone's runtime moves. Run it in a venv that has exactly one `executorch` version installed;
`python -m execubench host run` writes a JSON report and `host compare` diffs two of them.
"""

from __future__ import annotations

import hashlib
import json
import platform
from pathlib import Path

# Fixed, license-free prompts: the point is identical bytes across runtimes, not quality.
PROMPTS = (
    "The capital of France is",
    "Write one sentence about the sea.",
    "1, 2, 3, 4,",
)
MAX_NEW_TOKENS = 48


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def run(
    pte: Path,
    tokenizer: Path,
    prompts: tuple[str, ...] = PROMPTS,
    max_new_tokens: int = MAX_NEW_TOKENS,
    source: dict | None = None,
) -> dict:
    """One fresh runner per prompt, so no KV or recurrent state carries between prompts."""
    import importlib.metadata

    # The custom and quantized kernels register themselves on import; the runner needs them.
    from executorch.extension.llm.custom_ops import custom_ops  # noqa: F401
    from executorch.extension.llm.runner import GenerationConfig, TextLLMRunner
    from executorch.kernels import quantized  # noqa: F401

    results = []
    for prompt in prompts:
        runner = TextLLMRunner(str(pte), str(tokenizer))
        pieces: list[str] = []
        stats: dict = {}
        config = GenerationConfig(echo=False, max_new_tokens=max_new_tokens, temperature=0.0, num_bos=0, num_eos=0)
        runner.generate(
            prompt,
            config,
            token_callback=pieces.append,
            stats_callback=lambda s, out=stats: out.update(json.loads(s.to_json_string())),
        )
        results.append({"prompt": prompt, "pieces": pieces, "stats": stats})
    return {
        "executorch": importlib.metadata.version("executorch"),
        "torch": importlib.metadata.version("torch"),
        "source": source or {},
        "python": platform.python_version(),
        "machine": f"{platform.system()} {platform.machine()}",
        "pte": {"name": pte.name, "sha256": _sha256(pte)},
        "tokenizer": {"name": tokenizer.name, "sha256": _sha256(tokenizer)},
        "max_new_tokens": max_new_tokens,
        "results": results,
    }


def compare(a: dict, b: dict) -> dict:
    """Piece-by-piece agreement of two reports made from the same file and prompts."""
    if a["pte"]["sha256"] != b["pte"]["sha256"] or a["tokenizer"]["sha256"] != b["tokenizer"]["sha256"]:
        raise ValueError("reports are for different files")
    rows = []
    for ra, rb in zip(a["results"], b["results"], strict=True):
        if ra["prompt"] != rb["prompt"]:
            raise ValueError("reports used different prompts")
        first_diff = next(
            (i for i, (x, y) in enumerate(zip(ra["pieces"], rb["pieces"], strict=False)) if x != y),
            None if len(ra["pieces"]) == len(rb["pieces"]) else min(len(ra["pieces"]), len(rb["pieces"])),
        )
        rows.append(
            {
                "prompt": ra["prompt"],
                "identical": first_diff is None,
                "first_difference_at_piece": first_diff,
                "pieces": [len(ra["pieces"]), len(rb["pieces"])],
            }
        )
    return {
        "versions": [a["executorch"], b["executorch"]],
        "pte": a["pte"],
        "identical": all(r["identical"] for r in rows),
        "prompts": rows,
    }


def summary_markdown(folder: Path) -> str:
    """SUMMARY.md for a compatibility folder: one row per compared file, from its compare JSON."""
    rows = []
    for path in sorted(folder.glob("*.compare.json")):
        c = json.loads(path.read_text())
        diffs = [p["first_difference_at_piece"] for p in c["prompts"]]
        rows.append(
            f"| `{c['pte']['name']}` | {sum(p['identical'] for p in c['prompts'])} of {len(c['prompts'])} | "
            + ", ".join("same" if d is None else f"piece {d}" for d in diffs)
            + f" | {'yes' if c['identical'] else 'no'} |"
        )
    identical = sum(r.endswith("| yes |") for r in rows)
    return (
        f"# {folder.name}\n\n"
        "Generated by `python -m execubench host summary`; do not edit. Each file was run with\n"
        "ExecuTorch's TextLLMRunner, greedy, 48 new tokens, on three fixed prompts, under each\n"
        "runtime in its own venv on the same host; the reports beside this file hold every piece.\n\n"
        f"**{identical} of {len(rows)} files gave identical output under both runtimes.**\n\n"
        "| File | Prompts identical | First difference per prompt | Identical |\n"
        "|---|---|---|---|\n" + "\n".join(rows) + "\n"
    )
